theme: jekyll-theme-merlot
title: Sample Recipe Website
description: This website demonstrates how to easily publish and display a website
logo: https://cdn.loveandlemons.com/wp-content/uploads/2023/01/grilled-cheese.jpg
